/// include/rasi/asm/x86_64/assembler.hpp generated by run v0.1.2, do not edit.

#pragma once

#include <cstdint>
#include <vector>

namespace rasi::x86
{

struct Reg
{
	std::uint8_t idx;
	constexpr std::uint8_t index() const noexcept { return idx; }
	constexpr bool extended() const noexcept { return idx >= 8; }
};

struct Buffer
{
    std::vector<std::uint8_t> bytes;

    void emit(const std::uint8_t b)          { bytes.push_back(b); }
    void emit_u16(const std::uint16_t v)     { emit(v & 0xFF); emit((v >> 8) & 0xFF); }
    void emit_u32(const std::uint32_t v)     { emit(v & 0xFF); emit((v >> 8) & 0xFF); emit((v >> 16) & 0xFF); emit((v >> 24) & 0xFF); }
    void emit_u64(const std::uint64_t v)     { emit_u32(v & 0xFFFFFFFF); emit_u32(v >> 32); }
};

static constexpr std::uint8_t modrm(const std::uint8_t mod, const std::uint8_t reg, const std::uint8_t rm) noexcept
{ return (mod << 6) | ((reg & 7) << 3) | (rm & 7); }

static constexpr std::uint8_t rex(const bool W, const bool R, const bool X, const bool B) noexcept
{ return 0x40 | (W ? 0x08 : 0) | (R ? 0x04 : 0) | (X ? 0x02 : 0) | (B ? 0x01 : 0); }

template<typename Buffer> void emit_mov_rr64(Buffer& buf, Reg rd, Reg rs) noexcept
{
	buf.emit(rex(true, rs.extended(), false, rd.extended()));
	buf.emit(0x89);
	buf.emit(modrm(3, rs.index() & 7, rd.index() & 7));
}

template<typename Buffer> void emit_mov_ri64(Buffer& buf, Reg rd, std::uint64_t imm) noexcept
{
	buf.emit(rex(true, false, false, rd.extended()));
	buf.emit(0xB8 | (rd.index() & 7));
	buf.emit_u64(imm);
}

template<typename Buffer> void emit_mov_mi32(Buffer& buf, Reg rd, std::uint32_t imm) noexcept
{
	buf.emit(rex(true, false, false, rd.extended()));
	buf.emit(0xC7);
	buf.emit(modrm(3, 0, rd.index() & 7));
	buf.emit_u32(static_cast<std::uint32_t>(imm));
}

template<typename Buffer> void emit_add_rr64(Buffer& buf, Reg rd, Reg rs) noexcept
{
	buf.emit(rex(true, rs.extended(), false, rd.extended()));
	buf.emit(0x01);
	buf.emit(modrm(3, rs.index() & 7, rd.index() & 7));
}

template<typename Buffer> void emit_add_ri32(Buffer& buf, Reg rd, std::uint32_t imm) noexcept
{
	buf.emit(rex(true, false, false, rd.extended()));
	buf.emit(0x81);
	buf.emit(modrm(3, 0, rd.index() & 7));
	buf.emit_u32(static_cast<std::uint32_t>(imm));
}

template<typename Buffer> void emit_add_ri8(Buffer& buf, Reg rd, std::uint8_t imm) noexcept
{
	buf.emit(rex(true, false, false, rd.extended()));
	buf.emit(0x83);
	buf.emit(modrm(3, 0, rd.index() & 7));
	buf.emit(static_cast<std::uint8_t>(imm));
}

template<typename Buffer> void emit_ret(Buffer& buf) noexcept
{
	buf.emit(0xC3);
}

} // namespace rasi::x86
