/// dispatcher generated by rune v0.1.3, do not edit.

#pragma once

#include "include/rasi/asm/x86_64/assembler.hh"
#include <cstdint>
#include <span>
#include <string_view>

namespace rasi::x86
{

template<typename Buffer>
inline void dispatch(
    Buffer&                buf,
    const std::string_view op,
    std::span<const Reg>   regs,
    const std::int64_t     imm = 0 ) noexcept
{
    // add
    if ( op == "add" )
    {
        if ( regs.empty() && imm == 0 )
            { emit_add_rr64( buf, regs[0], regs[1] ); return; }
        if ( regs.empty() && imm >= -128 && imm <= 127 )
            { emit_add_ri8( buf, regs[0], static_cast<std::uint8_t>(imm) ); return; }
        if ( regs.empty() && imm >= -2147483648LL && imm <= 2147483647LL )
            { emit_add_ri32( buf, regs[0], static_cast<std::uint32_t>(imm) ); return; }
        return;
    }

    // mov
    if ( op == "mov" )
    {
        if ( regs.empty() && imm == 0 )
            { emit_mov_rr64( buf, regs[0], regs[1] ); return; }
        if ( regs.empty() && imm >= -2147483648LL && imm <= 2147483647LL )
            { emit_mov_mi32( buf, regs[0], static_cast<std::uint32_t>(imm) ); return; }
        if ( regs.empty() )
            { emit_mov_ri64( buf, regs[0], static_cast<std::uint64_t>(imm) ); return; }
        return;
    }

    // ret
    if ( op == "ret" )
    {
        if ( regs.empty() && imm == 0 )
            { emit_ret( buf ); return; }
        return;
    }

}

} // namespace rasi::x86
