#include "emitter.hh"

void emitter::emit( )
{
    m_out << "///\n"
             "/// This file was automatically generated by islec v" ISLEC_VERSION ".\n"
             "///\n";

    m_out << "bool lower( IsleContext &ctx, const rasi::Inst &inst )\n{\n";

    ++m_indent;
    emit_node( m_root );
    --m_indent;

    m_out << "}\n";
}

void emitter::emit_node( const dec_node &node )
{
    std::visit( [ & ]< typename Ty >( const Ty &n )
    {
        using T = std::decay_t< Ty >;

        if constexpr ( std::is_same_v< T, branch_node > ) emit_branch( n );
        else if constexpr ( std::is_same_v< T, leaf_node > )
            emit_leaf( n );
        else
            emit_fail( );
    }, node );
}

void emitter::emit_branch( const branch_node &node )
{
    indent( );
    m_out << "switch (inst.opcode) {\n";
    ++m_indent;

    for ( const auto &[ head, child ] : node.children )
    {
        indent( );
        m_out << "case rasi::InstKind::" << head << ": {\n";
        ++m_indent;

        emit_node( *child );

        --m_indent;
        indent( );
        m_out << "}\n";
    }

    indent( );
    m_out << "default:\n";
    ++m_indent;

    emit_fail( );

    --m_indent;
    --m_indent;

    indent( );
    m_out << "}\n";
}

void emitter::emit_leaf( const leaf_node &node ) const
{
    const auto &rule = *node.matched_rule;

    for ( auto i { 0uz }; i < rule.pattern.args.size( ); ++i )
    {
        const auto &[ head, args ] = rule.pattern.args[ i ];
        indent( );
        m_out << "const auto " << head << " = ctx.arg(inst, " << i << ");\n";
    }

    // if ( !rule.pattern.args.empty( ) ) m_out << '\n';

    indent( );
    m_out << "return ctx." << rule.body.head << "(";

    for ( auto i { 0uz }; i < rule.body.args.size( ); ++i )
    {
        if ( i > 0 ) m_out << ", ";
        m_out << rule.body.args[ i ].head;
    }

    m_out << ");\n";
}

void emitter::emit_fail( ) const
{
    indent( );
    m_out << "throw std::runtime_error(\"no rule matched\");\n";
}

void emitter::indent( ) const
{
    for ( auto i { 0uz }; i < m_indent; ++i )
        m_out << "    ";
}
