#include "emitter.hh"

void emitter::emit( )
{
    m_out << "#pragma once\n"
             "///\n"
             "/// This file was automatically generated by islec v" ISLEC_VERSION ".\n"
             "///\n"
             "#include <stdexcept>\n"
             "#include <optional>\n"
             "#include <rasi/asm/operand.hh>\n"
             "#include <rasi/isle/selector.hh>\n"
             "#include <rasi/ir/instruction.hh>\n\n";

    m_out << "inline std::optional<rasi::asm_::VReg> lower( rasi::isle::Selector &ctx, const rasi::Inst &inst )\n{\n";

    ++m_indent;
    emit_node( m_root );
    --m_indent;

    m_out << "}\n";
}

void emitter::emit_node( const dec_node &node )
{
    std::visit( [ & ]< typename Ty >( const Ty &n )
    {
        using T = std::decay_t< Ty >;

        if constexpr ( std::is_same_v< T, branch_node > ) emit_branch( n );
        else if constexpr ( std::is_same_v< T, leaf_node > )
            emit_leaf( n );
        else
            emit_fail( );
    }, node );
}

void emitter::emit_branch( const branch_node &node )
{
    indent( );
    m_out << "switch (inst.kind) {\n";
    ++m_indent;

    for ( const auto &[ head, child ] : node.children )
    {
        indent( );
        m_out << "case rasi::InstKind::" << head << ": {\n";
        ++m_indent;

        emit_node( *child );

        --m_indent;
        indent( );
        m_out << "}\n";
    }

    indent( );
    m_out << "default:\n";
    ++m_indent;

    emit_fail( );

    --m_indent;
    --m_indent;

    indent( );
    m_out << "}\n";
}

void emitter::emit_leaf( const leaf_node &node ) const
{
    const auto &rule      = *node.matched_rule;
    const auto  extr_name = rule.pattern.head;

    const extern_decl_node *decl = nullptr;
    if ( const auto iter = m_decls.find( extr_name ); iter != m_decls.end( ) ) decl = &iter->second;

    auto vreg_idx { 0 };
    for ( auto i { 0uz }; i < rule.pattern.args.size( ); ++i )
    {
        const auto &[ head, args ] = rule.pattern.args[ i ];
        const auto type_name       = ( decl && i < decl->params.size( ) ) ? decl->params[ i ] : "Value";
        const auto iter            = m_types.find( type_name );
        const auto is_prim         = iter != m_types.end( ) && std::holds_alternative< prim_type >( iter->second.kind );

        indent( );
        if ( is_prim ) m_out << "const auto " << head << " = ctx.imm(inst);\n";
        else           m_out << "const auto " << head << " = ctx.arg(inst, " << vreg_idx++ << ");\n";
    }

    // if ( !rule.pattern.args.empty( ) ) m_out << '\n';

    const bool has_return = decl && decl->ret != "void";

    indent( );
    if ( has_return ) m_out << "return ctx." << rule.body.head << "(";
    else m_out << "ctx." << rule.body.head << "(";

    for ( auto i { 0uz }; i < rule.body.args.size( ); ++i )
    {
        if ( i > 0 ) m_out << ", ";
        m_out << rule.body.args[ i ].head;
    }

    m_out << ");\n";
    if ( !has_return )
    {
        indent( );
        m_out << "return std::nullopt;\n";
    }
}

void emitter::emit_fail( ) const
{
    indent( );
    m_out << "throw std::runtime_error(\"no rule matched\");\n";
}

void emitter::indent( ) const
{
    for ( auto i { 0uz }; i < m_indent; ++i )
        m_out << "    ";
}
