/// inst_kind generated by rune v0.1.4, do not edit.

#pragma once

#include <cstdint>
#include <string_view>

namespace rasi::vcode
{

enum class MachInstKind : std::uint16_t
{
    mov_rr64,
    mov_ri64,
    mov_mi32,
    movsx_rr64,
    movzx_rr64,
    lea_rr64,
    push_r64,
    pop_r64,
    add_rr64,
    add_ri32,
    add_ri8,
    sub_rr64,
    sub_ri32,
    sub_ri8,
    imul_rr64,
    idiv_r64,
    udiv_r64,
    neg_r64,
    inc_r64,
    dec_r64,
    and_rr64,
    and_ri32,
    and_ri8,
    or_rr64,
    or_ri32,
    or_ri8,
    xor_rr64,
    xor_ri32,
    xor_ri8,
    not_r64,
    shl_ri8,
    shr_ri8,
    sar_ri8,
    cmp_rr64,
    cmp_ri32,
    cmp_ri8,
    test_rr64,
    test_ri32,
    jmp_r64,
    jmp_rel32,
    call_r64,
    call_rel32,
    store_mr64,
    load_rm64,
    ret,
    nop,
    ud2,
};

[[nodiscard]] inline std::string_view mach_inst_name( const MachInstKind k ) noexcept
{
    switch ( k )
    {
        case MachInstKind::mov_rr64: return "mov_rr64";
        case MachInstKind::mov_ri64: return "mov_ri64";
        case MachInstKind::mov_mi32: return "mov_mi32";
        case MachInstKind::movsx_rr64: return "movsx_rr64";
        case MachInstKind::movzx_rr64: return "movzx_rr64";
        case MachInstKind::lea_rr64: return "lea_rr64";
        case MachInstKind::push_r64: return "push_r64";
        case MachInstKind::pop_r64: return "pop_r64";
        case MachInstKind::add_rr64: return "add_rr64";
        case MachInstKind::add_ri32: return "add_ri32";
        case MachInstKind::add_ri8: return "add_ri8";
        case MachInstKind::sub_rr64: return "sub_rr64";
        case MachInstKind::sub_ri32: return "sub_ri32";
        case MachInstKind::sub_ri8: return "sub_ri8";
        case MachInstKind::imul_rr64: return "imul_rr64";
        case MachInstKind::idiv_r64: return "idiv_r64";
        case MachInstKind::udiv_r64: return "udiv_r64";
        case MachInstKind::neg_r64: return "neg_r64";
        case MachInstKind::inc_r64: return "inc_r64";
        case MachInstKind::dec_r64: return "dec_r64";
        case MachInstKind::and_rr64: return "and_rr64";
        case MachInstKind::and_ri32: return "and_ri32";
        case MachInstKind::and_ri8: return "and_ri8";
        case MachInstKind::or_rr64: return "or_rr64";
        case MachInstKind::or_ri32: return "or_ri32";
        case MachInstKind::or_ri8: return "or_ri8";
        case MachInstKind::xor_rr64: return "xor_rr64";
        case MachInstKind::xor_ri32: return "xor_ri32";
        case MachInstKind::xor_ri8: return "xor_ri8";
        case MachInstKind::not_r64: return "not_r64";
        case MachInstKind::shl_ri8: return "shl_ri8";
        case MachInstKind::shr_ri8: return "shr_ri8";
        case MachInstKind::sar_ri8: return "sar_ri8";
        case MachInstKind::cmp_rr64: return "cmp_rr64";
        case MachInstKind::cmp_ri32: return "cmp_ri32";
        case MachInstKind::cmp_ri8: return "cmp_ri8";
        case MachInstKind::test_rr64: return "test_rr64";
        case MachInstKind::test_ri32: return "test_ri32";
        case MachInstKind::jmp_r64: return "jmp_r64";
        case MachInstKind::jmp_rel32: return "jmp_rel32";
        case MachInstKind::call_r64: return "call_r64";
        case MachInstKind::call_rel32: return "call_rel32";
        case MachInstKind::store_mr64: return "store_mr64";
        case MachInstKind::load_rm64: return "load_rm64";
        case MachInstKind::ret: return "ret";
        case MachInstKind::nop: return "nop";
        case MachInstKind::ud2: return "ud2";
        default: return "unknown";
    }
}

} // namespace rasi::vcode
