/// inst_kind generated by rune v0.1.4, do not edit.

#pragma once

#include <cstdint>
#include <string_view>

namespace rasi::vcode
{

enum class MachInstKind : std::uint8_t
{
    mov,
    movsx,
    movzx,
    lea,
    push,
    pop,
    add,
    sub,
    imul,
    idiv,
    udiv,
    neg,
    inc,
    dec,
    and_,
    or_,
    xor_,
    not_,
    shl,
    shr,
    sar,
    cmp,
    test,
    jmp,
    call,
    ret,
    nop,
    ud2,
};

[[nodiscard]] inline std::string_view mach_inst_name( const MachInstKind k ) noexcept
{
    switch ( k )
    {
        case MachInstKind::mov: return "mov";
        case MachInstKind::movsx: return "movsx";
        case MachInstKind::movzx: return "movzx";
        case MachInstKind::lea: return "lea";
        case MachInstKind::push: return "push";
        case MachInstKind::pop: return "pop";
        case MachInstKind::add: return "add";
        case MachInstKind::sub: return "sub";
        case MachInstKind::imul: return "imul";
        case MachInstKind::idiv: return "idiv";
        case MachInstKind::udiv: return "udiv";
        case MachInstKind::neg: return "neg";
        case MachInstKind::inc: return "inc";
        case MachInstKind::dec: return "dec";
        case MachInstKind::and_: return "and";
        case MachInstKind::or_: return "or";
        case MachInstKind::xor_: return "xor";
        case MachInstKind::not_: return "not";
        case MachInstKind::shl: return "shl";
        case MachInstKind::shr: return "shr";
        case MachInstKind::sar: return "sar";
        case MachInstKind::cmp: return "cmp";
        case MachInstKind::test: return "test";
        case MachInstKind::jmp: return "jmp";
        case MachInstKind::call: return "call";
        case MachInstKind::ret: return "ret";
        case MachInstKind::nop: return "nop";
        case MachInstKind::ud2: return "ud2";
        default:                return "unknown";
    }
}

} // namespace rasi::vcode
