///
/// This file was automatically generated by islec v0.1.0.
///
bool lower( IsleContext &ctx, const rasi::Inst &inst )
{
    switch (inst.opcode) {
        case rasi::InstKind::iadd: {
            const auto lhs = ctx.arg(inst, 0);
            const auto rhs = ctx.arg(inst, 1);
            return ctx.emit_add(lhs, rhs);
        }
        case rasi::InstKind::isub: {
            const auto lhs = ctx.arg(inst, 0);
            const auto rhs = ctx.arg(inst, 1);
            return ctx.emit_sub(lhs, rhs);
        }
        case rasi::InstKind::neg: {
            const auto value = ctx.arg(inst, 0);
            return ctx.emit_neg(value);
        }
        default:
            throw std::runtime_error("no rule matched");
    }
}
